# Generated by Django 4.2.16 on 2024-12-22 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='birth',
            new_name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_name',
        ),
    ]
