# Generated by Django 4.2.16 on 2025-01-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0003_emailverificationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='users',
        ),
    ]
