# Generated by Django 4.2.16 on 2025-01-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0004_alter_customuser_email_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
