# Generated by Django 4.2.16 on 2025-02-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0007_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
