# Generated by Django 4.2.16 on 2025-03-02 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0008_alter_tweetmodel_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailverificationmodel',
            table='email_verifications',
        ),
        migrations.AlterModelTable(
            name='followmodel',
            table='follows',
        ),
        migrations.AlterModelTable(
            name='likemodel',
            table='likes',
        ),
        migrations.AlterModelTable(
            name='replymodel',
            table='replies',
        ),
        migrations.AlterModelTable(
            name='retweetmodel',
            table='retweets',
        ),
        migrations.AlterModelTable(
            name='tweetmodel',
            table='tweets',
        ),
    ]
