# Generated by Django 4.2.16 on 2025-03-02 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0009_alter_emailverificationmodel_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='usersssss',
        ),
    ]
