# Generated by Django 4.2.16 on 2025-03-02 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0010_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='users',
        ),
    ]
