# Generated by Django 4.2.16 on 2025-03-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0011_alter_customuser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='replymodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
