# Generated by Django 4.2.16 on 2025-03-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0012_replymodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='followmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
