# Generated by Django 4.2.16 on 2025-03-02 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0014_emailverificationmodel_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetmodel',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tweet', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
