# Generated by Django 4.2.16 on 2025-03-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0016_customuser_introduction_alter_followmodel_follower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='head_image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='イメージ画像_ヘッダー'),
        ),
    ]
