# Generated by Django 4.2.16 on 2025-03-06 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0017_customuser_head_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='place',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='web_site',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
