# Generated by Django 4.2.16 on 2025-03-23 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0019_alter_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replymodel',
            name='tweet',
        ),
        migrations.AddField(
            model_name='replymodel',
            name='origin_tweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_tweets', to='twitter_clone.tweetmodel'),
        ),
        migrations.AddField(
            model_name='replymodel',
            name='reply_tweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_tweets', to='twitter_clone.tweetmodel'),
        ),
    ]
