# Generated by Django 4.2.16 on 2025-03-23 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0020_remove_replymodel_tweet_replymodel_origin_tweet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replymodel',
            name='text',
        ),
    ]
