# Generated by Django 4.2.16 on 2025-03-23 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0021_remove_replymodel_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replymodel',
            name='user',
        ),
    ]
