# Generated by Django 4.2.16 on 2025-03-23 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0022_remove_replymodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='replymodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL),
        ),
    ]
