# Generated by Django 4.2.16 on 2025-03-23 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0023_replymodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replymodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
