# Generated by Django 4.2.16 on 2025-03-23 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0024_alter_replymodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replymodel',
            name='origin_tweet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='origin_tweets', to='twitter_clone.tweetmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='replymodel',
            name='reply_tweet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reply_tweets', to='twitter_clone.tweetmodel'),
            preserve_default=False,
        ),
    ]
