# Generated by Django 4.2.16 on 2025-03-30 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0025_alter_replymodel_origin_tweet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetmodel',
            name='is_retweet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tweetmodel',
            name='retweet',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter_clone.tweetmodel'),
        ),
    ]
