# Generated by Django 4.2.16 on 2025-03-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0026_tweetmodel_is_retweet_tweetmodel_retweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetmodel',
            name='sentense',
            field=models.TextField(blank=True, max_length=270, null=True),
        ),
    ]
