# Generated by Django 4.2.16 on 2025-05-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0028_bookmarkmodel_bookmarkmodel_bookmark_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
