# Generated by Django 4.2.16 on 2025-05-13 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0030_messageroommodel_messagemodel_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='messageroommodel',
            name='room_unique',
        ),
        migrations.RemoveField(
            model_name='messageroommodel',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='messageroommodel',
            name='user2',
        ),
        migrations.AddField(
            model_name='messageroommodel',
            name='participants',
            field=models.ManyToManyField(related_name='message_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
