# Generated by Django 4.2.16 on 2025-05-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0031_notificationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
