# Generated by Django 4.2.16 on 2025-05-03 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0032_notificationmodel_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationmodel',
            name='notice_target_id',
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='notice_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter_clone.tweetmodel'),
        ),
    ]
