# Generated by Django 4.2.16 on 2025-05-17 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0031_remove_messageroommodel_room_unique_and_more'),
        ('twitter_clone', '0033_remove_notificationmodel_notice_target_id_and_more'),
    ]

    operations = [
    ]
