# Generated by Django 4.2.16 on 2025-05-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0034_merge_20250517_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationmodel',
            old_name='notice_target',
            new_name='related_tweet',
        ),
        migrations.RemoveField(
            model_name='notificationmodel',
            name='action_flag',
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='action_type',
            field=models.CharField(choices=[('like', 'Like'), ('retweet', 'Retweet'), ('comment', 'Comment')], default='', max_length=8),
        ),
    ]
