from .base import *

EMAIL_BACKEND = env('EMAIL_BACKEND')
EMAIL_HOST = env('EMAIL_HOST_PRODUCTION')
EMAIL_PORT = env('EMAIL_PORT_PRODUCTION')
EMAIL_HOST_USER = env('EMAIL_HOST_USER_PRODUCTION')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD_PRODUCTION')
EMAIL_USE_SSL = False
EMAIL_USE_TLS = True